# Generated by Django 6.1.1 on 2026-09-10 14:31

import django.db.models.deletion
from django.db import migrations, models

import django_outbound_webhooks.validate_signing_secret
import django_outbound_webhooks.validate_webhook_url


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=2000,
                        validators=[
                            django_outbound_webhooks.validate_webhook_url.validate_webhook_url
                        ],
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Base64, optionally with the whsec_ prefix the specification uses.",
                        max_length=255,
                        validators=[
                            django_outbound_webhooks.validate_signing_secret.validate_signing_secret
                        ],
                    ),
                ),
                ("format_name", models.CharField(max_length=100)),
                ("format_version", models.PositiveSmallIntegerField()),
                ("tenant", models.CharField(blank=True, db_index=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "tenant"],
                        name="django_outb_is_acti_fb08a2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="django_outbound_webhooks.endpoint",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("endpoint", "event_name"),
                        name="unique_subscription_per_endpoint",
                    )
                ],
            },
        ),
    ]
