# Generated by Django 6.1.1 on 2026-09-11 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_outbound_webhooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(db_index=True, max_length=255)),
                ("url", models.URLField(max_length=2000)),
                ("source_event_id", models.BigIntegerField(db_index=True)),
                ("format_name", models.CharField(max_length=100)),
                ("format_version", models.PositiveSmallIntegerField()),
                ("outer_attempt", models.PositiveIntegerField()),
                ("inner_attempt", models.PositiveIntegerField()),
                ("request_body_sha256", models.CharField(max_length=64)),
                ("request_body_bytes", models.PositiveIntegerField()),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField()),
                ("verdict", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="django_outbound_webhooks.endpoint",
                    ),
                ),
            ],
            options={
                "ordering": ("message_id", "outer_attempt", "inner_attempt"),
                "indexes": [
                    models.Index(
                        fields=["message_id", "outer_attempt", "inner_attempt"],
                        name="django_outb_message_315e34_idx",
                    )
                ],
            },
        ),
    ]
