# Generated by Django 6.1.1 on 2026-09-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_outbound_webhooks", "0002_deliveryattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="consecutive_dead_deliveries",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="previous_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="previous_secret_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
